### ISSUE TITLE
add automated Windows test build

### ISSUE THREAD

**Issue by catdad** [catdad/grandma#112]

**Comment by catdad** [comment]
Created [a branch](https://github.com/catdad/grandma/tree/112-appveyor), but there are some failures. I don't feel like looking at them right now.

**Comment by catdad** [comment]
[appveyor build](https://ci.appveyor.com/project/catdad/grandma)

**Comment by catdad** [comment]
Tests that actually fail for faily reasons:

```bash
  1) [run:interactive] concurrent mode can have concurrency changed at runtime:
     Uncaught AssertionError: expected 1 to be at least 20
      at Immediate.<anonymous> (test\run.interactive.test.js:49:40)
  2) [run] runs tests in concurrency mode, outputting to a stream:
     Uncaught AssertionError: expected [ Array(3) ] to have a length of 5 but got 3
      at onOutput (test\run.test.js:114:57)
      at test\run.test.js:38:21
      at Stream.<anonymous> (node_modules\event-stream\index.js:318:20)
      at _end (node_modules\through\index.js:65:9)
      at Stream.stream.end (node_modules\through\index.js:74:5)
      at DestroyableTransform.onend (node_modules\readable-stream\lib\_stream_readable.js:504:10)
      at endReadableNT (node_modules\readable-stream\lib\_stream_readable.js:926:12)
      at _combinedTickCallback (internal/process/next_tick.js:74:11)
      at process._tickCallback (internal/process/next_tick.js:98:9)
```
