### ISSUE TITLE
grandma reports custom statistics that were not ended, causing stats to break

### ISSUE THREAD

**Issue by catdad** [catdad/grandma#66]
Sample report:

```
{"type":"header","epoch":1468240108698,"duration":60000,"rate":null,"concurrent":3,"targetCount":null,"name":null}
{"type":"report","report":{"fullTest":{"start":6.0636,"end":1029.950293,"duration":1023.8866930000002,"status":"failure","errorCode":"Failed to Upload Documet To ViewingSession: RequestError: Error: connect ECONNREFUSED 127.0.0.1:3000"},"ViewingSessionCreation":{"start":6.270659,"end":1030.522827,"duration":1024.252168,"status":"success"},"GETDocumentPageCount":{"start":1030.590211,"end":null,"duration":null,"status":"success"}},"id":0}
{"type":"report","report":{"fullTest":{"start":21.155217,"end":1035.556044,"duration":1014.4008269999999,"status":"failure","errorCode":"Failed to Upload Documet To ViewingSession: RequestError: Error: connect ECONNREFUSED 127.0.0.1:3000"},"ViewingSessionCreation":{"start":21.177083,"end":1035.681439,"duration":1014.5043559999999,"status":"success"},"GETDocumentPageCount":{"start":1035.684563,"end":null,"duration":null,"status":"success"}},"id":0}
```

The error:

```
C:\Workspace\Gitlab\prizmdoc-capacity-planning-tool\node_modules\grandma\lib\stats.js:15
            throw new Error('data[' + i + '] is not a number');
            ^

Error: data[0] is not a number
    at C:\Workspace\Gitlab\prizmdoc-capacity-planning-tool\node_modules\grandma\lib\stats.js:15:19
    at Array.forEach (native)
    at validateData (C:\Workspace\Gitlab\prizmdoc-capacity-planning-tool\node_modules\grandma\lib\stats.js:13:10)
    at Object.percentile (C:\Workspace\Gitlab\prizmdoc-capacity-planning-tool\node_modules\grandma\lib\stats.js:37:9)
    at Object.module.exports.iqr (C:\Workspace\Gitlab\prizmdoc-capacity-planning-tool\node_modules\grandma\lib\stats.js:52:32)
    at C:\Workspace\Gitlab\prizmdoc-capacity-planning-tool\node_modules\grandma\lib\report.js:155:29
    at C:\Workspace\Gitlab\prizmdoc-capacity-planning-tool\node_modules\lodash\lodash.js:12739:23
    at C:\Workspace\Gitlab\prizmdoc-capacity-planning-tool\node_modules\lodash\lodash.js:4411:15
    at baseForOwn (C:\Workspace\Gitlab\prizmdoc-capacity-planning-tool\node_modules\lodash\lodash.js:2654:24)
    at Function.mapValues (C:\Workspace\Gitlab\prizmdoc-capacity-planning-tool\node_modules\lodash\lodash.js:12738:7)
```

**Comment by catdad** [comment]
Published in 0.1.3.
